### ISSUE TITLE
Error in settings menu homey

### ISSUE THREAD

**Issue by DieBieEngineering** [matjaz/homey-better-presence#2]
On using this app I found a bug (i think). When normally navigating (my.athom -> login -> select my homey -> settings ) to the settings of this app my url becomes: 
http://192.168.1.105/manager/settings/#homey:manager:apps

And an error apears at the top of the menu.
![image](https://cloud.githubusercontent.com/assets/10616478/14561009/c060ec08-0313-11e6-9c0d-fb498962b1d5.png)

However when I navigate to the same menu with the url suggested on github:
http://homey.local/manager/settings/#homey:app:info.matjaz.presence

It does work:
![image](https://cloud.githubusercontent.com/assets/10616478/14561046/fae1724e-0313-11e6-8b9d-465b65bbc5eb.png)

**Comment by matjaz** [comment]
This is due CORS headers.
If you're accessing homey using IP, please update tracker config.json file.
Update `allowedOrigins` to your IP (and restart tracker app).

I'll add this step to instructions.
