### ISSUE TITLE
Error when setup

### ISSUE THREAD

**Issue by DieterKoblenz** [matjaz/homey-better-presence#4]
`{"data":null,"status":0,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://192.168.178.108:3000//.meta","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":""}`

I am getting the above error after inserting my server url. Using an advanced REST client I can see better presence working fine.

**Comment by matjaz** [comment]
Try removing `/` from URL. Also make sure you've setup CORS (`allowedOrigins`) correctly.
Please read https://github.com/matjaz/homey-better-presence/wiki/Setup

**Comment by DieterKoblenz** [comment]
Perfect, that was it. I thought homey.local would be sufficient but I had to enter its ip.
